baseURL                                      = "https://data.afro.co.ke/"
title                                        = "AfroData"
languageCode                                 = "en"
timezone                                     = "Africa/Nairobi"
timeout                                      = "600s"
copyright                                    = "{year} {title}"
pluralizeListTitles                          = false
enableRobotsTXT                              = true
disableKinds                                 = ["taxonomy","rss","term"]
[outputs]
  home = ["HTML","HEALTH","SCHOOLS","POWER","TRANSMISSION","CONSTITUENCIES"]
 [outputFormats]
   [outputFormats.HEALTH]
     baseName                                 = "health"
     isPlainText                              = true
     mediaType                                = 'application/json'
   [outputFormats.POWER]
     baseName                                 = "power"
     isPlainText                              = true
     mediaType                                = 'application/json'
   [outputFormats.SCHOOLS]
     baseName                                 = "schools"
     isPlainText                              = true
     mediaType                                = 'application/json'
   [outputFormats.TRANSMISSION]
     baseName                                 = "transmission"
     isPlainText                              = true
     mediaType                                = 'application/json'
   [outputFormats.CONSTITUENCIES]
     baseName                                 = "constituencies"
     isPlainText                              = true
     mediaType                                = 'application/json'
   # Extra output format for XML sitemap if sitemap gets to over 50k pages
   # [outputFormats.siteLorem]
    # MediaType             = "application/xml"
    #BaseName              = "sitehealth"
    #suffix                = "xml"
    #IsHTML                = false
    #IsPlainText           = false
    #noUgly                = true
    #Rel                   = "alternate"
[markup]
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block                                = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.superscript]
          enable                            = true
[caches]
  [caches.getresource]
    dir                                    = ':resourceDir'
    maxAge                                 = "720h"
  [caches.images]
    dir                                    = ':resourceDir/_gen'
    maxAge                                 = "1440h"
  [caches.assets]
    dir                                    = ':resourceDir/_gen'
    maxAge                                 = -1
[image]
  quality                                  = 100
[build]
  noJSConfigInAssets                       = true
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'